create new classes
Julia3202/java-explore-with-me pull request #2
Opened 2023-12-09 14:23 UTC by Julia3202

2023-12-18 21:21 UTC, Frilock requested changes
Добрый вечер, комментарии в коде =)

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/category/AdminCategoryController.java
> +@Validated
Для чего эта аннотация? У вас Valid уже есть у ряда методов

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/category/dao/CategoryRepository.java
> +@Repository
Нет смысла ставить аннотации над интерфейсами, работать будет и так

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/utils/CategoryValidator.java
> +public class CategoryValidator {
А почему бы данный метод не сделать статичным и использовать там где вам нужно без создания экземпляра? Бины тут не инжектятся, будет довольно просто 
В других классах данного пакета аналогичная идея
Код будет более читаемым
или что то смущает?

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        validatorService.uniqueName(newCategoryDto);
На мой взгляд, если вы проверяете только имя, то и передавайте имя на вход метода.
Кроме того, если возвращаемым значением является признак, то в названии лучше добавлять is - isUniqueName и тд

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        categoryFromDto.setId(id);
А почему в мапере сразу не сетите?

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        if (from == null) {
Такие проверки лучше в контролере оставить, прям сразу на приеме обьекта

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +            throw new ConflictException("Удаление невозможно,к категории относится " + eventList.size() + " событий.");
после запятой пробел =)

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilation/AdminCompilationController.java
> +        log.info("Поступил запрос на изменение подборки с id={}, updateCompilation={}", compId, updateCompilationDto);
Логируйте и другие методы контролеров тогда =)

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilation/PublicCompilationController.java
> +                                        @Valid @RequestParam(defaultValue = "0") Integer from,
Тут нужно использовать не аннотацию Valid, а другие аннотации из Java валидации

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilation/dao/CompilationRepository.java
> +@Repository
Лишняя аннотация

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilation/dao/CompilationRepository.java
> +    @Query("select c " +
А зачем вам тут использовать Query?  В названии метода не укладываетесь? Вроде простые запросы

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilation/dto/CompilationMapper.java
> +    @Mapping(target = "events", source = "events")
По моему, если названия у полей одинаковые то можно маппинг такой не указывать

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilation/model/Compilation.java
> +    private List<Event> events;
Коллекцию можно сразу инициализировать, чтобы на нул не проверять. Но тут на ваше усмотрение

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilation/model/Compilation.java
> +            joinColumns = {@JoinColumn(name = "compilation_id")})
По моему тут лишние открывающие и закрывающие скобки, идея не подвечивает?

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilation/model/Compilation.java
> +    @Column
А почему для данного поля размерность не указали?

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        List<Event> events = newCompilationDto.getEvents() != null &&
Для проверки коллекции на нот нул и на пустоту, можно использовать методы библиотеки apache commons 
CollectionUtils.isBlank

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/event/AdminEventController.java
> +                                           @Valid @RequestParam(name = "from", defaultValue = "0") Integer from,
Тут должны быть другие аннотации, использование аннотации Valid в данном случае не особо верное

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/event/PrivateEventController.java
> +@Validated
По моему лишняя аннотация

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/event/dao/EventRepository.java
> +@Repository
Лишняя аннотация

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/event/model/Event.java
> +    @Column(nullable = false)
А почему не указываете размерность?

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/event/service/PrivateEventServiceImpl.java
> +        if (event.getState().equals(State.PUBLISHED)) {
Енамы правильнее сравнивать через стандартные операторы

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/event/service/PublicEventServiceImpl.java
> +        if (!event.getState().equals(State.PUBLISHED)) {
Енамы правильнее сравнивать через стандартные операторы

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/exception/ErrorResponse.java
> +    private final String error;
Можно пару аннотаций от ломбока повесить и упростить класс =)

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/location/dao/LocationRepository.java
> +@Repository
Лишняя аннотация

2023-12-18 21:21 UTC, Frilock commented on main-service/src/main/java/ru/practicum/request/dao/RequestRepository.java
> +@Repository
Лишняя аннотация

2023-12-19 09:19 UTC, Julia3202 commented on main-service/src/main/java/ru/practicum/compilation/dto/CompilationMapper.java
> +    @Mapping(target = "events", source = "events")
Тут дело не в названии а типах данных, у newCompilationDto events -это список id event.

2023-12-19 10:38 UTC, Julia3202 commented on main-service/src/main/java/ru/practicum/compilation/model/Compilation.java
> +            joinColumns = {@JoinColumn(name = "compilation_id")})
Нет, не подсвечивает. Перепроверила,вроде все верно

2023-12-19 20:26 UTC, Frilock approved these changes
Принято, в целом все довольно хорошо

2023-12-19 20:35 UTC, merged